version: 2 

sources:
  - name: raw
    schema: gz_raw_data 
    description: greenweez raw data source
    tables:
        - name: product
          identifier: raw_gz_product
          description: products of greenweez
          columns: 
            - name: products_id
              description: Primary key of the table
              tests: 
                - unique
                - not_null
                  
        - name: ship
          identifier: raw_gz_ship
          description: shipping info 
          columns:
            - name: orders_id
              description: Primary key of the table
              tests:
                - unique
                - not_null
                    
        
        - name: sales
          identifier: raw_gz_tables
          description: Greenweez sold products 
          columns: 
            - name: date_date
              description: date
            - name: orders_id
              description: orders
            - name: pdt_id
              description: products name
            - name: revenue
              description: revenue from the orders
            - name: quantity
              description: order quantity
          tests:
            - unique:
                column_name: "(orders_id || '-' || pdt_id)"